### ISSUE TITLE
Input in Java Exercises not working with gVisor

### ISSUE THREAD

**Issue by MrSerth** [openHPI/poseidon#284]
Some time ago, we enabled gVisor on all Nomad agents for various reasons. The setup with gVisor turned out to be somewhat slower than just relying on `runc`, but otherwise worked as expected. During that time period, we also saw that (almost) everything worked as expected, including Turtle graphics and interactive input in Python. 

However, recently, we noticed an issue with the input and Java exercises when gVisor is enabled that we cannot explain yet. Instead of processing the input as expect, we see a `java.util.NoSuchElementException`:

```
Exception in thread "main" java.util.NoSuchElementException: No line found
	at java.base/java.util.Scanner.nextLine(Scanner.java:1651)
	at HalloWelt.read(HalloWelt.java:20)
	at HalloWelt.main(HalloWelt.java:8)
make: *** [Makefile:3: run] Error 1
```

The following example allows reproducing the issue:

```java
import java.util.Scanner;

public class HalloWelt {
    public static void main(String[] args) {
        System.out.println("Output on stdout");
        System.err.println("Output on stderr");

        String input = read();
        System.out.println(input);
        System.err.println(input);
    }

    private static String read() {
        Scanner scanner = new Scanner(System.in);

        // We need to send a JSON, so that CodeOcean asks for input.
        System.out.println("{\"data\": \"\", \"stream\": \"stdin\", \"cmd\": \"input\"}");

        // This should be the input.
        String line = scanner.nextLine();
        System.out.println("Received: " + line);

        // We don't parse the JSON and instead just use the same position (very nasty!)
        String substring = line.substring(24, line.length()-2);
        System.out.println("Parsed input: " + substring);

        return substring;
    }
}
```

**Expected behavior:**

The following output was received with **gVisor being disabled**.

<img width="676" alt="without gVisor" src="https://user-images.githubusercontent.com/7300329/218726929-d0f2f791-19bc-4734-832b-bb2412020b5a.png">

<details>
 <summary>Poseidon log</summary>

```
time="2023-02-14T11:45:28.475584Z" level=debug code=410 duration="643.436µs" method=PATCH path=/api/v1/runners/10-564aacd7-ac5b-11ed-96d1-fa163e67d105/files user_agent="Faraday v2.7.4"
time="2023-02-14T11:45:28.483160Z" level=debug code=200 duration="269.32µs" method=POST path=/api/v1/runners user_agent="Faraday v2.7.4"
time="2023-02-14T11:45:28.704721Z" level=debug code=204 duration=201.133292ms method=PATCH path=/api/v1/runners/10-eb3eeeea-ac55-11ed-96d1-fa163e67d105/files user_agent="Faraday v2.7.4"
time="2023-02-14T11:45:28.708697Z" level=debug code=200 duration="298.816µs" method=POST path=/api/v1/runners/10-eb3eeeea-ac55-11ed-96d1-fa163e67d105/execute user_agent="Faraday v2.7.4"
time="2023-02-14T11:45:28.736865Z" level=info msg="Running execution" executionID=31955761-2256-4c7e-bfab-b0f033a9b6d7 package=api runnerId=10-eb3eeeea-ac55-11ed-96d1-fa163e67d105
time="2023-02-14T11:45:28.737107Z" level=trace msg="Sending message to client" message="&{start  0}" package=ws
time="2023-02-14T11:45:29.638683Z" level=trace msg="Sending message to client" message="&{stdout Output on stdout\r\n 0}" package=ws
time="2023-02-14T11:45:29.638800Z" level=trace msg="Sending message to client" message="&{stderr Output on stderr\r\n 0}" package=ws
time="2023-02-14T11:45:29.655627Z" level=trace msg="Sending message to client" message="&{stdout {\"data\": \"\", \"stream\": \"stdin\", \"cmd\": \"input\"}\r\n 0}" package=ws
time="2023-02-14T11:45:29.658681Z" level=debug msg="Runner started" id=10-13f0af9f-ac5d-11ed-b96f-fa163e67d105 package=runner startupDuration=688.822515ms
time="2023-02-14T11:45:30.646887Z" level=trace msg="Received message from client" message="{\"cmd\":\"result\",\"data\":\"<my custom input>\"}\n" package=ws
time="2023-02-14T11:45:30.653222Z" level=trace msg="Sending message to client" message="&{stdout {\"cmd\":\"result\",\"data\":\"<my custom input>\"}\r\n 0}" package=ws
time="2023-02-14T11:45:30.653415Z" level=trace msg="Sending message to client" message="&{stderr <my custom input>\r\n 0}" package=ws
time="2023-02-14T11:45:30.654202Z" level=trace msg="Sending message to client" message="&{stdout Received: {\"cmd\":\"result\",\"data\":\"<my custom input>\"}\r\nParsed input: <my custom input>\r\n<my custom input>\r\n 0}" package=ws
time="2023-02-14T11:45:30.720014Z" level=info msg="Execution returned" package=api
time="2023-02-14T11:45:30.720239Z" level=debug code=200 duration=1.983588766s method=GET path=/api/v1/runners/10-eb3eeeea-ac55-11ed-96d1-fa163e67d105/websocket user_agent=
time="2023-02-14T11:45:30.721540Z" level=trace msg="Sending message to client" message="&{exit  0}" package=ws
time="2023-02-14T11:45:30.933125Z" level=debug code=200 duration=206.220324ms method=GET path=/api/v1/runners/10-eb3eeeea-ac55-11ed-96d1-fa163e67d105/files user_agent="Faraday v2.7.4"
```
</details>

**Actual behavior:**

The following output was received with **gVisor being enabled**.

<img width="678" alt="with gVisor" src="https://user-images.githubusercontent.com/7300329/218727039-376e57cb-b5bd-458f-9152-4caad493aa02.png">

<details>
 <summary>Poseidon log (with Sentry in debug mode)</summary>

```
[Sentry] 2023/02/14 11:40:52 Using explicit sampling decision from StartSpan/StartTransaction: SampledTrue
time="2023-02-14T11:40:52.285927Z" level=debug code=410 duration="77.921µs" method=PATCH path=/api/v1/runners/3-65cbe80b-ac5b-11ed-b68e-fa163e45684d/files user_agent="Faraday v2.7.4"
[Sentry] 2023/02/14 11:40:52 Sending transaction [1d56869656a44d1682c7eb9bdad53533] to o4504634145636352.ingest.sentry.io project: 6077585
[Sentry] 2023/02/14 11:40:52 Using explicit sampling decision from StartSpan/StartTransaction: SampledTrue
time="2023-02-14T11:40:52.289599Z" level=debug code=200 duration="564.676µs" method=POST path=/api/v1/runners user_agent="Faraday v2.7.4"
[Sentry] 2023/02/14 11:40:52 Sending transaction [44a4ad85589345e8b33d2c2c11db7e69] to o4504634145636352.ingest.sentry.io project: 6077585
[Sentry] 2023/02/14 11:40:52 Using explicit sampling decision from StartSpan/StartTransaction: SampledTrue
time="2023-02-14T11:40:52.616128Z" level=debug code=204 duration=294.624711ms method=PATCH path=/api/v1/runners/3-57f2ebb9-ac5c-11ed-997f-fa163e45684d/files user_agent="Faraday v2.7.4"
[Sentry] 2023/02/14 11:40:52 Sending transaction [369c080b90e14e42a4a02cbc21cb2088] to o4504634145636352.ingest.sentry.io project: 6077585
[Sentry] 2023/02/14 11:40:52 Using explicit sampling decision from StartSpan/StartTransaction: SampledTrue
time="2023-02-14T11:40:52.625918Z" level=debug code=200 duration="219.179µs" method=POST path=/api/v1/runners/3-57f2ebb9-ac5c-11ed-997f-fa163e45684d/execute user_agent="Faraday v2.7.4"
[Sentry] 2023/02/14 11:40:52 Sending transaction [9a034f0ac3cd492babb622cd8fd66b12] to o4504634145636352.ingest.sentry.io project: 6077585
[Sentry] 2023/02/14 11:40:52 Using explicit sampling decision from StartSpan/StartTransaction: SampledTrue
time="2023-02-14T11:40:52.651022Z" level=info msg="Running execution" executionID=d23f8ed6-df99-417e-a2d0-66e53daa6bc2 package=api runnerId=3-57f2ebb9-ac5c-11ed-997f-fa163e45684d
time="2023-02-14T11:40:52.651222Z" level=trace msg="Sending message to client" message="&{start  0}" package=ws
time="2023-02-14T11:40:53.608779Z" level=debug msg="Runner started" id=3-6f50d7e6-ac5c-11ed-997f-fa163e45684d package=runner startupDuration=1.077743329s
time="2023-02-14T11:40:55.984005Z" level=trace msg="Sending message to client" message="&{stdout Output on stdout\r\n 0}" package=ws
time="2023-02-14T11:40:55.985304Z" level=trace msg="Sending message to client" message="&{stderr Output on stderr 0}" package=ws
time="2023-02-14T11:40:55.985635Z" level=trace msg="Sending message to client" message="&{stderr \r\n 0}" package=ws
time="2023-02-14T11:40:56.084614Z" level=trace msg="Sending message to client" message="&{stdout {\"data\": \"\", \"stream\": \"stdin\", \"cmd\": \"input\"} 0}" package=ws
time="2023-02-14T11:40:56.084841Z" level=trace msg="Sending message to client" message="&{stdout \r\n 0}" package=ws
time="2023-02-14T11:40:58.347871Z" level=trace msg="Received message from client" message="{\"cmd\":\"result\",\"data\":\"<my custom input>\"}\n" package=ws
time="2023-02-14T11:40:58.351528Z" level=trace msg="Sending message to client" message="&{stdout {\"cmd\":\"result\",\"data\":\"<my custom input>\"}\r\n 0}" package=ws
time="2023-02-14T11:40:58.359248Z" level=trace msg="Sending message to client" message="&{stderr Exception in thread \"main\"  0}" package=ws
time="2023-02-14T11:40:58.360071Z" level=trace msg="Sending message to client" message="&{stderr java.util.NoSuchElementException: No line found 0}" package=ws
time="2023-02-14T11:40:58.360957Z" level=trace msg="Sending message to client" message="&{stderr \r\n 0}" package=ws
time="2023-02-14T11:40:58.362433Z" level=trace msg="Sending message to client" message="&{stderr \tat java.base/java.util.Scanner.nextLine(Scanner.java:1651)\r\n 0}" package=ws
time="2023-02-14T11:40:58.363560Z" level=trace msg="Sending message to client" message="&{stderr \tat HalloWelt.read(HalloWelt.java:20)\r\n\tat HalloWelt.main(HalloWelt.java:8)\r\n 0}" package=ws
time="2023-02-14T11:40:58.378332Z" level=trace msg="Sending message to client" message="&{stderr make: *** [Makefile:3: run] Error 1\r\n 0}" package=ws
time="2023-02-14T11:40:58.469945Z" level=info msg="Execution returned" package=api
time="2023-02-14T11:40:58.470119Z" level=debug code=200 duration=5.819233283s method=GET path=/api/v1/runners/3-57f2ebb9-ac5c-11ed-997f-fa163e45684d/websocket user_agent=
[Sentry] 2023/02/14 11:40:58 Sending transaction [24fcdac3526f48b09ece216ac5b5eb71] to o4504634145636352.ingest.sentry.io project: 6077585
time="2023-02-14T11:40:58.471924Z" level=trace msg="Sending message to client" message="&{exit  2}" package=ws
[Sentry] 2023/02/14 11:40:58 Using explicit sampling decision from StartSpan/StartTransaction: SampledTrue
time="2023-02-14T11:40:58.836216Z" level=debug code=200 duration=326.097916ms method=GET path=/api/v1/runners/3-57f2ebb9-ac5c-11ed-997f-fa163e45684d/files user_agent="Faraday v2.7.4"
[Sentry] 2023/02/14 11:40:58 Sending transaction [2e5061b858424dc6946e7b8e91bbbadd] to o4504634145636352.ingest.sentry.io project: 6077585
```
</details>

---

I am unsure what causes this issue and why we are seeing it only for Java exercises (and not for Python). While I would have argue that the JVM should be unaffected, as it works on different levels of abstractions, the problem is easily reproducable by enabling and disabling gVisor. I would assume something is not working as expected with passing the input to the Java program, even though Python works as expected. We probably need to do further research and maybe also search for (similar) issues other faced when using gVisor.

**Comment by MrSerth** [comment]
Let's first start with a minimal reproduction example without relying on CodeOcean / Poseidon / ...

**Comment by mpass99** [comment]
This [Dockerfile](https://github.com/openHPI/poseidon/files/10755268/Dockerfile.txt) allows to reproduce the error without CodeOcean/Poseidon.

Some observations:
- `docker run --runtime=runc gvisortest sh -c "echo ABC | java HelloWorld"` no error
- `docker run --runtime=runsc gvisortest sh -c "echo ABC | java HelloWorld"` no error
- `docker run --runtime=runc gvisortest` expected error
- `docker run --runtime=runsc gvisortest` expected error
- `docker run --runtime=runc -it gvisortest` no error
- `docker run --runtime=runsc -it gvisortest` **error**
- `docker run --runtime=runsc -i gvisortest` no error

**Comment by mpass99** [comment]
It behaves the same with this [Dockerfile](https://github.com/openHPI/poseidon/files/10755409/Dockerfile.txt) using the official [`openjdk:latest`](https://hub.docker.com/layers/library/openjdk/latest/images/sha256-fe05457a5e9b9403f8e72eeba507ae80a4237d2d2d3f219fa62ceb128482a9ee) image.

**Comment by MrSerth** [comment]
Awesome, thanks! Jan and I checked the Dockerfile (using the `openjdk:latest`) and both of us were easily able to reproduce the issue. I combined everything in one command, just to have that available quickly:

```shell
docker run --rm --runtime=runsc -it $(docker build -q .)
```

Let's collect some [debug logs](https://gvisor.dev/docs/user_guide/debugging/) and prepare a bug report we can send them.

**Comment by MrSerth** [comment]
I just made the observation that hitting CTRL+D on the keyboard during the input is waiting also produces the `java.util.NoSuchElementException` (and thereby the same behavior).

**Comment by mpass99** [comment]
I've filled their bug report form with the information we have. Wdyt?
Here are the debug logs. The file upload of their form is disabled for that part..
- [runsc.log.20230217-211828.220888.create.txt](https://github.com/openHPI/poseidon/files/10771931/runsc.log.20230217-211828.220888.create.txt)
- [runsc.log.20230217-211828.277437.gofer.txt](https://github.com/openHPI/poseidon/files/10771932/runsc.log.20230217-211828.277437.gofer.txt)
- [runsc.log.20230217-211828.278541.boot.txt](https://github.com/openHPI/poseidon/files/10771933/runsc.log.20230217-211828.278541.boot.txt)
- [runsc.log.20230217-211828.548907.start.txt](https://github.com/openHPI/poseidon/files/10771936/runsc.log.20230217-211828.548907.start.txt)
- [runsc.log.20230217-211833.428571.delete.txt](https://github.com/openHPI/poseidon/files/10771937/runsc.log.20230217-211833.428571.delete.txt)
- [runsc.log.20230217-211833.508054.delete.txt](https://github.com/openHPI/poseidon/files/10771938/runsc.log.20230217-211833.508054.delete.txt)

---

## StdIn Exception with PTY running Java

### Description

Containerized Java programs that try to read from the `StdIn` throw the `java.util.NoSuchElementException` when providing input via an interactive session in a pseudo-TTY only when using `runsc` (not with `runc`).

### Steps to reproduce

1. Create the [Dockerfile](https://github.com/google/gvisor/files/10771835/Dockerfile.txt)

``` Dockerfile
FROM openjdk:latest

LABEL description='gVisor Input Exception'
WORKDIR /tmp

RUN echo -e 'import java.util.Scanner;\n\
\n\
public class HelloWorld {\n\
    public static void main(String[] args) {\n\
        System.out.println("Output on stdout");\n\
        System.err.println("Output on stderr");\n\
\n\
        System.out.print("Your Input:");\n\
        Scanner scanner = new Scanner(System.in);\n\
        String line = scanner.nextLine();\n\
        System.out.println("Received: " + line);\n\
    }\n\
}\n' > HelloWorld.java

RUN javac HelloWorld.java

CMD java HelloWorld
```

2. Build and run the Dockerfile: 
``` sh
docker run --rm --runtime=runsc -it $(docker build -q .)
```

3. Provide and submit input

### runsc version

``` sh
runsc version release-20230130.0
spec: 1.0.2-dev
```

### docker version (if using docker)

``` sh
Client: Docker Engine - Community
 Version:           23.0.1
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        a5ee5b1
 Built:             Thu Feb  9 19:47:01 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       bc3805a
  Built:            Thu Feb  9 19:47:01 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.16
  GitCommit:        31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### uname

``` sh
Linux mp 5.15.0-60-generic #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### kubectl (if using Kubernetes)
 
_No response_

### repo state (if built from source)

_No response_

### runsc debug logs (if available)

`runsc.log.*.gofer.txt`:
``` log
D0217 21:18:33.372411       1 connection.go:127] sock read failed, closing connection: EOF
```

`runsc.log.*.boot.txt`:
``` log
I0217 21:18:33.357451   91846 strace.go:567] [   1:   2] java E write(0x2 host:[1], 0x7ffb6b218140 "java.util.NoSuchElementException: No line found\n", 0x30)
```

**Comment by MrSerth** [comment]
I like it and just made very few adjustments to make the situation more clear (pointing out that other languages are not affected) and slightly adjusting the indention.

**Comment by mpass99** [comment]
Submitted @ https://github.com/google/gvisor/issues/8544

**Comment by MrSerth** [comment]
A new gVisor [release-20230529.0](https://github.com/google/gvisor/releases/tag/release-20230529.0) was just created, potentially containing a bug fix for the issue we reported.

@mpass99 Would you mind verifying, commenting, and re-enabling gVisor (through a PR), please?

**Comment by MrSerth** [comment]
We deployed the new gVisor release to CodeOcean and were able to verify that the issue no longer occurs.
