### ISSUE TITLE
Crash: Concurrent map read and map write

### ISSUE THREAD

**Issue by MrSerth** [openHPI/poseidon#573]
Today, we experienced another crash of Poseidon (reported with [POSEIDON-4P](https://codeocean.sentry.io/issues/4524919408/)). Inspecting the log shows the following snippet:

```
Apr 12 09:33:00 poseidon-terraform poseidon[637]: fatal error: concurrent map read and map write
Apr 12 09:33:00 poseidon-terraform poseidon[637]: goroutine 28 [running]:
Apr 12 09:33:00 poseidon-terraform poseidon[637]: github.com/openHPI/poseidon/internal/nomad.handleEvaluationEvent(0xc000562b10, 0x0?)
Apr 12 09:33:00 poseidon-terraform poseidon[637]: #011/opt/poseidon/internal/nomad/nomad.go:323 +0x12c
Apr 12 09:33:00 poseidon-terraform poseidon[637]: github.com/openHPI/poseidon/internal/nomad.(*APIClient).WatchEventStream.func1(0xc006d8f080)
Apr 12 09:33:00 poseidon-terraform poseidon[637]: #011/opt/poseidon/internal/nomad/nomad.go:237 +0xb2
Apr 12 09:33:00 poseidon-terraform poseidon[637]: github.com/openHPI/poseidon/internal/nomad.receiveAndHandleNomadAPIEvents(0xc0006b5440, 0xc006cfd5e8)
Apr 12 09:33:00 poseidon-terraform poseidon[637]: #011/opt/poseidon/internal/nomad/nomad.go:305 +0x1a4
Apr 12 09:33:00 poseidon-terraform poseidon[637]: github.com/openHPI/poseidon/internal/nomad.(*APIClient).WatchEventStream(0xc000562ae0, {0x12d8a70, 0xc0001508c0}, 0xc0004a6a80)
Apr 12 09:33:00 poseidon-terraform poseidon[637]: #011/opt/poseidon/internal/nomad/nomad.go:246 +0x11f
Apr 12 09:33:00 poseidon-terraform poseidon[637]: github.com/openHPI/poseidon/internal/runner.(*NomadRunnerManager).SynchronizeRunners(0xc000562ba0, {0x12d8a70, 0xc0001508c0})
Apr 12 09:33:00 poseidon-terraform poseidon[637]: #011/opt/poseidon/internal/runner/nomad_manager.go:110 +0x127
Apr 12 09:33:00 poseidon-terraform poseidon[637]: main.synchronizeNomad.func1({0x12d8a70, 0xc0001508c0})
Apr 12 09:33:00 poseidon-terraform poseidon[637]: #011/opt/poseidon/cmd/poseidon/main.go:365 +0x99
Apr 12 09:33:00 poseidon-terraform poseidon[637]: github.com/openHPI/poseidon/internal/environment.(*NomadEnvironmentManager).KeepEnvironmentsSynced.func1()
Apr 12 09:33:00 poseidon-terraform poseidon[637]: #011/opt/poseidon/internal/environment/nomad_manager.go:183 +0xee
Apr 12 09:33:00 poseidon-terraform poseidon[637]: github.com/openHPI/poseidon/pkg/util.RetryConstantAttemptsWithContext.retryConstant.func1()
Apr 12 09:33:00 poseidon-terraform poseidon[637]: #011/opt/poseidon/pkg/util/util.go:38 +0x42
Apr 12 09:33:00 poseidon-terraform poseidon[637]: github.com/openHPI/poseidon/pkg/util.retryAttempts(0x7fffffffffffffff, 0xc006cfdca8)
Apr 12 09:33:00 poseidon-terraform poseidon[637]: #011/opt/poseidon/pkg/util/util.go:54 +0xd2
Apr 12 09:33:00 poseidon-terraform poseidon[637]: github.com/openHPI/poseidon/pkg/util.RetryConstantAttemptsWithContext(0x0?, {0x12d8a70?, 0xc0001508c0?}, 0x0?)
Apr 12 09:33:00 poseidon-terraform poseidon[637]: #011/opt/poseidon/pkg/util/util.go:81 +0x5b
Apr 12 09:33:00 poseidon-terraform poseidon[637]: github.com/openHPI/poseidon/internal/environment.(*NomadEnvironmentManager).KeepEnvironmentsSynced(0x0?, 0x0?, {0x12d8a70, 0xc0001508c0})
Apr 12 09:33:00 poseidon-terraform poseidon[637]: #011/opt/poseidon/internal/environment/nomad_manager.go:175 +0x94
Apr 12 09:33:00 poseidon-terraform poseidon[637]: created by main.synchronizeNomad in goroutine 1
Apr 12 09:33:00 poseidon-terraform poseidon[637]: #011/opt/poseidon/cmd/poseidon/main.go:356 +0x10e
Apr 12 09:33:00 poseidon-terraform poseidon[637]: goroutine 1 [select, 4734 minutes]:
Apr 12 09:33:00 poseidon-terraform poseidon[637]: main.shutdownOnOSSignal(0xc00037a0f0, {0x12d8a70, 0xc0001508c0}, 0xc000560e40)
Apr 12 09:33:00 poseidon-terraform poseidon[637]: #011/opt/poseidon/cmd/poseidon/main.go:420 +0x18b
Apr 12 09:33:00 poseidon-terraform poseidon[637]: main.main()
Apr 12 09:33:00 poseidon-terraform poseidon[637]: #011/opt/poseidon/cmd/poseidon/main.go:459 +0x2a5
# ............
```

Consequentially, Poseidon restarted:

```
Apr 12 09:33:30 poseidon-terraform systemd[1]: poseidon.service: Scheduled restart job, restart counter is at 1.
Apr 12 09:33:30 poseidon-terraform systemd[1]: Stopped Poseidon.
Apr 12 09:33:30 poseidon-terraform systemd[1]: poseidon.service: Consumed 11h 5min 26.237s CPU time.
Apr 12 09:33:30 poseidon-terraform systemd[1]: Starting Poseidon...
```

**Comment by MrSerth** [comment]
Your analysis and fix look plausible. Since the stack trace copied over refers to `nomad.go:323` and you've touched that, I think we might be on a good way to fix the error. Let's give it a try, deploy it and close this issue.
