### ISSUE TITLE
Panic: Send on closed channel

### ISSUE THREAD

**Issue by MrSerth** [openHPI/poseidon#618]
On June 20, 2024 at 03:55:33UTC, we saw another unsuccessful Poseidon exit: [POSEIDON-4P](https://codeocean.sentry.io/issues/4524919408/)

This issue was caused by a message being "sent on a closed channel" resulting in a panic.

<details>
<summary>Log</summary>

```
2024-06-20T03:53:41.928615+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:53:41.928212Z" level=debug code=410 duration="153.402µs" method=PATCH path=/api/v1/runners/29-234ad63f-2ea7-11ef-9b69-fa163efe023e/files user_agent="Farada
y v2.9.1"
2024-06-20T03:53:41.930916+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:53:41.930160Z" level=debug code=200 duration="57.43µs" method=POST path=/api/v1/runners user_agent="Faraday v2.9.1"
2024-06-20T03:53:42.034454+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:53:42.034349Z" level=debug msg="Ignoring duplicate event" allocID=3c65982b-c102-c1ac-2fb7-389023827c9e package=nomad
2024-06-20T03:53:42.035044+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:53:42.034917Z" level=debug msg="Ignoring duplicate event" allocID=3c65982b-c102-c1ac-2fb7-389023827c9e package=nomad
2024-06-20T03:53:42.035090+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:53:42.035058Z" level=debug msg="Ignoring unknown allocation" allocID=1402f16c-ca14-91ea-0938-b621adce578e package=nomad
2024-06-20T03:53:42.042896+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:53:42.042622Z" level=debug msg="Handle Allocation Event" ClientStatus=pending DesiredStatus=run NextAllocation= PrevAllocation= alloc_id=2f517520-11f7-cd46-5126-9181ad1b7e9a package=nomad
2024-06-20T03:53:42.042964+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:53:42.042669Z" level=debug msg="Ignoring duplicate event" allocID=2f517520-11f7-cd46-5126-9181ad1b7e9a package=nomad
2024-06-20T03:53:42.079201+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:53:42.079072Z" level=debug code=204 duration=141.257508ms method=PATCH path=/api/v1/runners/29-f4e1742e-2e74-11ef-9b69-fa163efe023e/files user_agent="Faraday v2.9.1"
2024-06-20T03:53:42.134307+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:53:42.134191Z" level=debug code=200 duration="80.414µs" method=POST path=/api/v1/runners/29-f4e1742e-2e74-11ef-9b69-fa163efe023e/execute user_agent="Faraday v2.9.1"
2024-06-20T03:53:42.153019+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:53:42.152754Z" level=info msg="Running execution" environment_id=29 executionID=6abe6c3d-05ef-4bad-a170-94d011d4de7d package=api runner_id=29-f4e1742e-2e74-11ef-9b69-fa163efe023e
2024-06-20T03:53:42.840426+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:53:42.840304Z" level=debug msg="Handle Allocation Event" ClientStatus=running DesiredStatus=run NextAllocation= PrevAllocation= alloc_id=2f517520-11f7-cd46-5126-9181ad1b7e9a package=nomad
2024-06-20T03:53:42.840519+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:53:42.840347Z" level=debug msg="Runner started" package=runner runner_id=29-af287fe0-2eb8-11ef-9b69-fa163efe023e startupDuration=797.701581ms
2024-06-20T03:53:42.841384+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:53:42.841341Z" level=debug msg="Ignoring unknown allocation" allocID=fd19845f-7f39-7773-183d-796b91771b6b package=nomad
2024-06-20T03:53:47.350214+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:53:47.349831Z" level=debug code=204 duration="51.167µs" method=GET path=/api/v1/health user_agent="Faraday v2.9.1"
2024-06-20T03:53:54.974629+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:53:54.974239Z" level=debug code=204 duration="50.937µs" method=GET path=/api/v1/health user_agent="check_http/v2.2 (monitoring-plugins 2.2)"
2024-06-20T03:54:12.154018+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:54:12.153335Z" level=info msg="Execution returned" environment_id=29 package=api runner_id=29-f4e1742e-2e74-11ef-9b69-fa163efe023e
2024-06-20T03:54:12.154441+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:54:12.153439Z" level=debug code=200 duration=30.000762177s method=GET path=/api/v1/runners/29-f4e1742e-2e74-11ef-9b69-fa163efe023e/websocket user_agent=
2024-06-20T03:54:12.165445+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:54:12.165265Z" level=debug msg="Destroying Runner" destroy_reason="the client wants to stop the runner" package=runner runner_id=29-f4e1742e-2e74-11ef-9b69-fa163efe023e
2024-06-20T03:54:12.172412+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:54:12.171859Z" level=debug code=204 duration=6.60711ms method=DELETE path=/api/v1/runners/29-f4e1742e-2e74-11ef-9b69-fa163efe023e user_agent="Faraday v2.9.1"
2024-06-20T03:54:12.257244+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:54:12.257056Z" level=debug msg="Execution terminated after SIGQUIT" package=runner runner_id=29-f4e1742e-2e74-11ef-9b69-fa163efe023e
2024-06-20T03:54:16.640120+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:54:16.639614Z" level=debug code=410 duration="212.877µs" method=PATCH path=/api/v1/runners/29-f4e1742e-2e74-11ef-9b69-fa163efe023e/files user_agent="Faraday v2.9.1"
2024-06-20T03:54:16.642220+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:54:16.641814Z" level=debug code=200 duration="62.929µs" method=POST path=/api/v1/runners user_agent="Faraday v2.9.1"
2024-06-20T03:54:16.669780+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:54:16.668503Z" level=debug msg="Handle Allocation Event" ClientStatus=pending DesiredStatus=run NextAllocation= PrevAllocation= alloc_id=f891942d-6294-095e-d344-ef01a55b85a3 package=nomad
2024-06-20T03:54:16.679775+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:54:16.679678Z" level=debug msg="Ignoring duplicate event" allocID=f891942d-6294-095e-d344-ef01a55b85a3 package=nomad
2024-06-20T03:54:16.680528+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:54:16.680475Z" level=debug msg="Ignoring duplicate event" allocID=ceb4d550-e621-bf2c-63dc-f7ab829b6369 package=nomad
2024-06-20T03:54:16.806082+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:54:16.805906Z" level=debug code=204 duration=154.436109ms method=PATCH path=/api/v1/runners/29-be301304-2eb6-11ef-9b69-fa163efe023e/files user_agent="Faraday v2.9.1"
2024-06-20T03:54:16.857479+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:54:16.857325Z" level=debug code=200 duration="79.37µs" method=POST path=/api/v1/runners/29-be301304-2eb6-11ef-9b69-fa163efe023e/execute user_agent="Faraday v2.9.1"
2024-06-20T03:54:16.869751+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:54:16.869680Z" level=info msg="Running execution" environment_id=29 executionID=d41ad249-c960-4a53-9087-bbc574b0d360 package=api runner_id=29-be301304-2eb6-11ef-9b69-fa163efe023e
2024-06-20T03:54:17.072419+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:54:17.072320Z" level=debug msg="Ignoring duplicate event" allocID=f891942d-6294-095e-d344-ef01a55b85a3 package=nomad
2024-06-20T03:54:17.303149+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:54:17.303049Z" level=debug msg="Handle Allocation Event" ClientStatus=running DesiredStatus=run NextAllocation= PrevAllocation= alloc_id=f891942d-6294-095e-d344-ef01a55b85a3 package=nomad
2024-06-20T03:54:17.303339+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:54:17.303087Z" level=debug msg="Runner started" package=runner runner_id=29-c3d912d0-2eb8-11ef-9b69-fa163efe023e startupDuration=634.555998ms
2024-06-20T03:54:33.667458+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:54:33.666912Z" level=info msg="Execution returned" environment_id=29 package=api runner_id=29-be301304-2eb6-11ef-9b69-fa163efe023e
2024-06-20T03:54:33.667549+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:54:33.666974Z" level=debug code=200 duration=16.797343814s method=GET path=/api/v1/runners/29-be301304-2eb6-11ef-9b69-fa163efe023e/websocket user_agent=
2024-06-20T03:54:33.829785+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:54:33.827948Z" level=debug code=200 duration=148.468499ms method=GET path=/api/v1/runners/29-be301304-2eb6-11ef-9b69-fa163efe023e/files user_agent="Faraday v2.9.1"
2024-06-20T03:54:47.349546+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:54:47.349145Z" level=debug code=204 duration="62.328µs" method=GET path=/api/v1/health user_agent="Faraday v2.9.1"
2024-06-20T03:54:53.361278+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:54:53.360819Z" level=debug code=204 duration=134.930764ms method=PATCH path=/api/v1/runners/29-be301304-2eb6-11ef-9b69-fa163efe023e/files user_agent="Faraday v2.9.1"
2024-06-20T03:54:53.408793+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:54:53.408645Z" level=debug code=200 duration="76.586µs" method=POST path=/api/v1/runners/29-be301304-2eb6-11ef-9b69-fa163efe023e/execute user_agent="Faraday v2.9.1"
2024-06-20T03:54:53.422285+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:54:53.422225Z" level=info msg="Running execution" environment_id=29 executionID=57f7b4ba-244b-410b-b151-782bc9671efe package=api runner_id=29-be301304-2eb6-11ef-9b69-fa163efe023e
2024-06-20T03:54:54.976378+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:54:54.975830Z" level=debug code=204 duration="56.067µs" method=GET path=/api/v1/health user_agent="check_http/v2.2 (monitoring-plugins 2.2)"
2024-06-20T03:55:07.287405+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:55:07.287015Z" level=info msg="Execution returned" environment_id=29 package=api runner_id=29-be301304-2eb6-11ef-9b69-fa163efe023e
2024-06-20T03:55:07.289255+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:55:07.287090Z" level=debug code=200 duration=13.86491944s method=GET path=/api/v1/runners/29-be301304-2eb6-11ef-9b69-fa163efe023e/websocket user_agent=
2024-06-20T03:55:07.440785+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:55:07.439525Z" level=debug code=200 duration=139.459062ms method=GET path=/api/v1/runners/29-be301304-2eb6-11ef-9b69-fa163efe023e/files user_agent="Faraday
 v2.9.1"
2024-06-20T03:55:33.544565+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:55:33.544147Z" level=debug code=410 duration="58.541µs" method=PATCH path=/api/v1/runners/10-37416af3-1c57-11ef-bac6-fa163efe023e/files user_agent="Faraday
 v2.9.1"
2024-06-20T03:55:33.545954+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:55:33.545888Z" level=debug code=200 duration="70.454µs" method=POST path=/api/v1/runners user_agent="Faraday v2.9.1"
2024-06-20T03:55:33.696150+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:55:33.696000Z" level=debug code=204 duration=140.410044ms method=PATCH path=/api/v1/runners/10-6fd1d308-2e3b-11ef-9b69-fa163efe023e/files user_agent="Farad
ay v2.9.1"
2024-06-20T03:55:33.734788+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:55:33.734227Z" level=debug msg="Ignoring duplicate event" allocID=408b9c0e-414f-d3e6-581f-4c1ffc77d0bc package=nomad
2024-06-20T03:55:33.734873+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:55:33.734449Z" level=debug msg="Ignoring duplicate event" allocID=408b9c0e-414f-d3e6-581f-4c1ffc77d0bc package=nomad
2024-06-20T03:55:33.735198+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:55:33.735166Z" level=debug msg="Ignoring unknown allocation" allocID=39981933-49a9-df66-2a49-555162e90a65 package=nomad
2024-06-20T03:55:33.743625+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:55:33.743571Z" level=debug msg="Handle Allocation Event" ClientStatus=pending DesiredStatus=run NextAllocation= PrevAllocation= alloc_id=a44df560-aecb-1483
-ab6d-95be4d3f8b50 package=nomad
2024-06-20T03:55:33.745019+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:55:33.744984Z" level=debug msg="Ignoring duplicate event" allocID=a44df560-aecb-1483-ab6d-95be4d3f8b50 package=nomad
2024-06-20T03:55:33.745170+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:55:33.745120Z" level=debug code=200 duration="47.22µs" method=POST path=/api/v1/runners/10-6fd1d308-2e3b-11ef-9b69-fa163efe023e/execute user_agent="Faraday
 v2.9.1"
2024-06-20T03:55:33.763134+00:00 poseidon-terraform poseidon[156783]: time="2024-06-20T03:55:33.763009Z" level=info msg="Running execution" environment_id=10 executionID=a6d45e9f-2f6d-4ca4-8113-7d3bf3851272 package=api runner_id=10-6fd1d308-2e3b
-11ef-9b69-fa163efe023e
2024-06-20T03:55:33.802609+00:00 poseidon-terraform poseidon[156783]: panic: send on closed channel
2024-06-20T03:55:33.802695+00:00 poseidon-terraform poseidon[156783]: goroutine 1032708 [running]:
2024-06-20T03:55:33.802753+00:00 poseidon-terraform poseidon[156783]: github.com/openHPI/poseidon/internal/nomad.handleEvaluationEvent({0x11c5448, 0xc0000880c0}, 0xc0059878c0?)
2024-06-20T03:55:33.802789+00:00 poseidon-terraform poseidon[156783]: #011/opt/poseidon/internal/nomad/nomad.go:327 +0x1b8
2024-06-20T03:55:33.802816+00:00 poseidon-terraform poseidon[156783]: github.com/openHPI/poseidon/internal/nomad.(*APIClient).WatchEventStream.func1(0xc0059878c0)
2024-06-20T03:55:33.802844+00:00 poseidon-terraform poseidon[156783]: #011/opt/poseidon/internal/nomad/nomad.go:238 +0xbf
2024-06-20T03:55:33.802868+00:00 poseidon-terraform poseidon[156783]: github.com/openHPI/poseidon/internal/nomad.receiveAndHandleNomadAPIEvents(0xc004cc88a0, 0xc004d87f50)
2024-06-20T03:55:33.802891+00:00 poseidon-terraform poseidon[156783]: #011/opt/poseidon/internal/nomad/nomad.go:306 +0x1a4
2024-06-20T03:55:33.802915+00:00 poseidon-terraform poseidon[156783]: github.com/openHPI/poseidon/internal/nomad.(*APIClient).WatchEventStream(0xc000088140, {0x11bff00, 0xc00297edc0}, 0xc0006b9fb8)
2024-06-20T03:55:33.802980+00:00 poseidon-terraform poseidon[156783]: #011/opt/poseidon/internal/nomad/nomad.go:247 +0x11f
2024-06-20T03:55:33.803016+00:00 poseidon-terraform poseidon[156783]: github.com/openHPI/poseidon/internal/nomad.(*APIClient).MonitorEvaluation.func1()
2024-06-20T03:55:33.803039+00:00 poseidon-terraform poseidon[156783]: #011/opt/poseidon/internal/nomad/nomad.go:210 +0x58
2024-06-20T03:55:33.803062+00:00 poseidon-terraform poseidon[156783]: created by github.com/openHPI/poseidon/internal/nomad.(*APIClient).MonitorEvaluation in goroutine 1032704
2024-06-20T03:55:33.803085+00:00 poseidon-terraform poseidon[156783]: #011/opt/poseidon/internal/nomad/nomad.go:209 +0x232
2024-06-20T03:55:33.845852+00:00 poseidon-terraform systemd[1]: poseidon.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
2024-06-20T03:55:33.855443+00:00 poseidon-terraform poseidon-exit-alert.sh[230715]: Poseidon exited unsuccessful. Sending Sentry Event
2024-06-20T03:55:33.863415+00:00 poseidon-terraform poseidon-exit-alert.sh[230717]: Event dispatched: 265d616b-4567-4ffb-b5b3-169e0196d223
2024-06-20T03:55:33.865080+00:00 poseidon-terraform systemd[1]: poseidon.service: Failed with result 'exit-code'.
2024-06-20T03:55:33.865488+00:00 poseidon-terraform systemd[1]: poseidon.service: Consumed 6h 2min 31.036s CPU time, 22.4M memory peak, 0B memory swap peak.
2024-06-20T03:55:35.969688+00:00 poseidon-terraform systemd[1]: poseidon.service: Scheduled restart job, restart counter is at 1.
2024-06-20T03:55:35.975064+00:00 poseidon-terraform systemd[1]: Starting poseidon.service - Poseidon...
```

</details>

**Comment by mpass99** [comment]
For this case, the influxDB logs are missing as Poseidon panics. However, we see that the evaluation channel caused it and can conclude that it received a second event for the same evaluation.

https://github.com/openHPI/poseidon/blob/e2fd5024612bd167edce08ba73ab2214270a8edd/internal/nomad/nomad.go#L328-L329

Let's go through the usual evaluation process.

<details><summary>Nomad Events</summary>
<p>

| type | key | timestamp | _value |
| --- | --- | --- | --- |
| EvaluationUpdated | bda63d26-9d0e-5ec6-bef1-3de9308ee80f | 03:27:40.871776902 | map\[Evaluation:map\[CreateIndex:1.039655e+06 CreateTime:1.71885091689065e+18 ID:bda63d26-9d0e-5ec6-bef1-3de9308ee80f JobID:22-46fe0b06-1d10-11ef-bac6-fa163efe023e ModifyIndex:1.039655e+06 ModifyTime:1.71885091689065e+18 Namespace:poseidon NodeID:cb04341c-ea7d-5300-1a40-356801c6c1e8 NodeModifyIndex:1.039654e+06 Priority:50 Status:pending TriggeredBy:node-update Type:batch\]\] |
| EvaluationUpdated | bda63d26-9d0e-5ec6-bef1-3de9308ee80f | 03:27:40.899272784 | map\[Evaluation:map\[CreateIndex:1.039655e+06 CreateTime:1.71885091689065e+18 ID:bda63d26-9d0e-5ec6-bef1-3de9308ee80f JobID:22-46fe0b06-1d10-11ef-bac6-fa163efe023e ModifyIndex:1.039697e+06 ModifyTime:1.7188509169399316e+18 Namespace:poseidon NodeID:cb04341c-ea7d-5300-1a40-356801c6c1e8 NodeModifyIndex:1.039654e+06 Priority:50 QueuedAllocations:map\[config:0 default-group:0\] SnapshotIndex:1.039686e+06 Status:complete TriggeredBy:node-update Type:batch\]\] |
| EvaluationUpdated | bda63d26-9d0e-5ec6-bef1-3de9308ee80f | 03:38:40.657313248 | map\[Evaluation:map\[CreateIndex:1.039655e+06 CreateTime:1.71885091689065e+18 ID:bda63d26-9d0e-5ec6-bef1-3de9308ee80f JobID:22-46fe0b06-1d10-11ef-bac6-fa163efe023e ModifyIndex:1.039697e+06 ModifyTime:1.7188509169399316e+18 Namespace:poseidon NodeID:cb04341c-ea7d-5300-1a40-356801c6c1e8 NodeModifyIndex:1.039654e+06 Priority:50 QueuedAllocations:map\[config:0 default-group:0\] SnapshotIndex:1.039686e+06 Status:complete TriggeredBy:node-update Type:batch\]\] |
| EvaluationUpdated | bda63d26-9d0e-5ec6-bef1-3de9308ee80f | 03:39:48.162347646 | map\[Evaluation:map\[CreateIndex:1.039655e+06 CreateTime:1.71885091689065e+18 ID:bda63d26-9d0e-5ec6-bef1-3de9308ee80f JobID:22-46fe0b06-1d10-11ef-bac6-fa163efe023e ModifyIndex:1.039697e+06 ModifyTime:1.7188509169399316e+18 Namespace:poseidon NodeID:cb04341c-ea7d-5300-1a40-356801c6c1e8 NodeModifyIndex:1.039654e+06 Priority:50 QueuedAllocations:map\[config:0 default-group:0\] SnapshotIndex:1.039686e+06 Status:complete TriggeredBy:node-update Type:batch\]\] |
| EvaluationUpdated | bda63d26-9d0e-5ec6-bef1-3de9308ee80f | 03:53:41.945534807 | map\[Evaluation:map\[CreateIndex:1.039655e+06 CreateTime:1.71885091689065e+18 ID:bda63d26-9d0e-5ec6-bef1-3de9308ee80f JobID:22-46fe0b06-1d10-11ef-bac6-fa163efe023e ModifyIndex:1.039697e+06 ModifyTime:1.7188509169399316e+18 Namespace:poseidon NodeID:cb04341c-ea7d-5300-1a40-356801c6c1e8 NodeModifyIndex:1.039654e+06 Priority:50 QueuedAllocations:map\[config:0 default-group:0\] SnapshotIndex:1.039686e+06 Status:complete TriggeredBy:node-update Type:batch\]\] |

</p>
</details> 

- We have one `pending` evaluation that is filtered out:
https://github.com/openHPI/poseidon/blob/e2fd5024612bd167edce08ba73ab2214270a8edd/internal/nomad/nomad.go#L323

- We have one `complete` event that is passed to the `resultChannel` and closes it.

- We have three more `complete` events that race with the defer, triggered by the first `complete` event, that removes the `resultChannel`:
https://github.com/openHPI/poseidon/blob/e2fd5024612bd167edce08ba73ab2214270a8edd/internal/nomad/nomad.go#L202


We might assume that this is one of the rare cases where this race got unlucky.

A fix without further architecture reconsideration would be to move the removal of the `resultChannel` to the closing of it. As the event stream handling is synchronous there cannot be multiple `handleEvaluationEvent` processes accessing the evaluation channel.

**Comment by MrSerth** [comment]
Sounds good :+1:
